name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '52 0 4 4 *'
    - cron: '41 4 4 4 *'
    - cron: '55 8 4 4 *'
    - cron: '24 13 4 4 *'
    - cron: '32 17 4 4 *'
    - cron: '6 1 5 4 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push