name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '22 0 8 4 *'
    - cron: '17 3 8 4 *'
    - cron: '53 5 8 4 *'
    - cron: '35 7 8 4 *'
    - cron: '8 9 8 4 *'
    - cron: '40 11 8 4 *'
    - cron: '19 12 8 4 *'
    - cron: '52 15 8 4 *'
    - cron: '13 17 8 4 *'
    - cron: '27 19 8 4 *'
    - cron: '40 20 8 4 *'
    - cron: '37 22 8 4 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push