name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '37 1 24 7 *'
    - cron: '53 2 24 7 *'
    - cron: '21 4 24 7 *'
    - cron: '58 6 24 7 *'
    - cron: '59 8 24 7 *'
    - cron: '25 11 24 7 *'
    - cron: '0 12 24 7 *'
    - cron: '58 15 24 7 *'
    - cron: '20 16 24 7 *'
    - cron: '1 19 24 7 *'
    - cron: '28 0 25 7 *'
    - cron: '41 3 25 7 *'
    - cron: '3 5 25 7 *'
    - cron: '58 7 25 7 *'
    - cron: '26 9 25 7 *'
    - cron: '33 11 25 7 *'
    - cron: '18 13 25 7 *'
    - cron: '40 15 25 7 *'
    - cron: '48 17 25 7 *'
    - cron: '36 18 25 7 *'
    - cron: '14 1 26 7 *'
    - cron: '59 3 26 7 *'
    - cron: '37 5 26 7 *'
    - cron: '52 7 26 7 *'
    - cron: '1 9 26 7 *'
    - cron: '6 10 26 7 *'
    - cron: '16 12 26 7 *'
    - cron: '7 14 26 7 *'
    - cron: '51 16 26 7 *'
    - cron: '16 19 26 7 *'
    - cron: '59 0 27 7 *'
    - cron: '22 2 27 7 *'
    - cron: '37 4 27 7 *'
    - cron: '8 6 27 7 *'
    - cron: '37 9 27 7 *'
    - cron: '57 10 27 7 *'
    - cron: '40 13 27 7 *'
    - cron: '30 14 27 7 *'
    - cron: '25 17 27 7 *'
    - cron: '52 19 27 7 *'
    - cron: '13 0 28 7 *'
    - cron: '1 2 28 7 *'
    - cron: '45 5 28 7 *'
    - cron: '13 7 28 7 *'
    - cron: '4 8 28 7 *'
    - cron: '43 10 28 7 *'
    - cron: '40 13 28 7 *'
    - cron: '1 15 28 7 *'
    - cron: '58 17 28 7 *'
    - cron: '54 19 28 7 *'
    - cron: '18 0 29 7 *'
    - cron: '34 3 29 7 *'
    - cron: '45 5 29 7 *'
    - cron: '12 6 29 7 *'
    - cron: '49 9 29 7 *'
    - cron: '26 11 29 7 *'
    - cron: '37 13 29 7 *'
    - cron: '26 14 29 7 *'
    - cron: '11 17 29 7 *'
    - cron: '36 19 29 7 *'
    - cron: '32 1 30 7 *'
    - cron: '27 3 30 7 *'
    - cron: '19 5 30 7 *'
    - cron: '53 7 30 7 *'
    - cron: '44 9 30 7 *'
    - cron: '8 11 30 7 *'
    - cron: '16 13 30 7 *'
    - cron: '12 14 30 7 *'
    - cron: '21 17 30 7 *'
    - cron: '11 19 30 7 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set Git Identity
        run: |
          git config --global user.name "Jain Divyam Arvindkumar"
          git config --global user.email "jaindivyam200@gmail.com"

      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push